' pphdecoding P12-D region_reopen e2e
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-D region_reopen
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12d_region_reopen_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12d_region_e2e_out.pph", False
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set QR2_ = Doc_.QueryFaceRegionByName("P12DRegion")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "qr2__alive=" & CStr(Not (QR2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
