' pphdecoding P12-D facet e2e
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-D facet
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12d_facet_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set MG4_ = Doc_.CreateMeshingGroup
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg4__alive=" & CStr(Not (MG4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.ImportCADAsFacet "D:/training/cgns/pphdecoding/tests/box/box.x_t", MG4_
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/p12d_facet_e2e_out.pph"
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
