' pphdecoding P12-E reopen e2e
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-E reopen
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12e_reopen_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12e_wrapping_e2e_out.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set Octree_ = MG_.GetOctree
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "octree__alive=" & CStr(Not (Octree_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If Octree_ Is Nothing Then Set Octree_ = MG_.GetOctree
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
If Octree_ Is Nothing Then Set Octree_ = MG_.GetOctree
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
If Octree_ Is Nothing Then Set Octree_ = MG_.GetOctree
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
