' pphdecoding P12-F coord
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-F coord e2e
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12f_coord_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12f_coord_in.pph", False
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set CP_ = Doc_.CreateCoordinatesSpecifiedPart("P12FCoordPart")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "cp__alive=" & CStr(Not (CP_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/p12f_coord_out.pph"
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
