' pphdecoding P12-F actran
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-F actran e2e
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12f_actran_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12f_actran_in.pph", False
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.SetModeMesh
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.SetActiveMeshingGroup 0, 0
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
actran_ret_ = MG_.CreateActranFilesMonitor("D:/training/cgns/pphdecoding/_p12f_e2e/actran_out")
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "actran_ret=" & CStr(actran_ret_) & " err=" & CStr(Err.Number)
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "actran_files=" & CStr(fso_.GetFolder("D:/training/cgns/pphdecoding/_p12f_e2e/actran_out").Files.Count) & " err=0"
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
