' pphdecoding P12-I cvrestore e2e
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-I cvrestore
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12i_cvrestore_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set SN6_ = Doc_.ImportPatchAsCAD("D:/training/cgns/pphdecoding/_p12i_e2e/p12i_patch2_sample_cube.stl")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn6__alive=" & CStr(Not (SN6_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG1_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg1__alive=" & CStr(Not (MG1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
MG1_.RecognizeClosedVolume False
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
Set MD1_ = MG1_.GetMDL
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "md1__alive=" & CStr(Not (MD1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Cvs1_ = MD1_.GetClosedVolumes()
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
If IsArray(Cvs1_) Then out_.WriteLine "cvs1_ub=" & CStr(UBound(Cvs1_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "cvs1_ub=NA err=0"
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/p12i_cv2b_out.pph"
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12i_cv2b_out.pph", False
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
MG2_.RecognizeClosedVolume False
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
Set MD2_ = MG2_.GetMDL
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "md2__alive=" & CStr(Not (MD2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If MD2_ Is Nothing Then Set MD2_ = MG2_.GetMDL
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "md2_alive=" & CStr(Not (MD2_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
If MD2_ Is Nothing Then Set MD2_ = MG2_.GetMDL
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "md2_alive=" & CStr(Not (MD2_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
Av1_ = MD2_.IsClosedVolumeRestorationAvailable
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "av1=" & CStr(Av1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
Str2_ = MD2_.GetStoredClosedVolumes(False)
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
If IsArray(Str2_) Then out_.WriteLine "str2_ub=" & CStr(UBound(Str2_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "str2_ub=NA err=0"
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
LB1_ = 0
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
If IsArray(Str2_) Then LB1_ = LBound(Str2_)
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
Cur2_ = MD2_.GetClosedVolumes()
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
If IsArray(Cur2_) Then out_.WriteLine "cur2_ub=" & CStr(UBound(Cur2_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "cur2_ub=NA err=0"
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
LB0_ = 0
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
If IsArray(Cur2_) Then LB0_ = LBound(Cur2_)
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
Set Cand_ = MD2_.GetRestorationCandidateOfClosedVolume(LB0_, True)
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "cand__alive=" & CStr(Not (Cand_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set Dest_ = Cur2_(LB0_)
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "dest__alive=" & CStr(Not (Dest_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set Src_ = Str2_(LB1_)
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "src__alive=" & CStr(Not (Src_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Dim Pairs_(1)
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
Set Pairs_(0) = Dest_
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
Set Pairs_(1) = Src_
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
RRet_ = MD2_.RestoreClosedVolumes(True, Pairs_)
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "restore_ret=" & CStr(RRet_) & " err=" & CStr(Err.Number)
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/p12i_cv_restore2_out.pph"
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
