' pphdecoding P12-I cvstore e2e
' generated by pphdecoding automation/vbs_bridge.py

' pphdecoding P12-I cvstore
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/p12i_cvstore_e2e.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/p12i_cv1_out.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
MG_.RecognizeClosedVolume False
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
Set MDL_ = MG_.GetMDL
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mdl__alive=" & CStr(Not (MDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Cvs_ = MDL_.GetClosedVolumes()
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
If IsArray(Cvs_) Then out_.WriteLine "cvs_ub=" & CStr(UBound(Cvs_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "cvs_ub=NA err=0"
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
Av0_ = MDL_.IsClosedVolumeRestorationAvailable
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "av0=" & CStr(Av0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
SRet_ = MDL_.StoreClosedVolumes()
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "store_ret=" & CStr(SRet_) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Str_ = MDL_.GetStoredClosedVolumes(False)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
If IsArray(Str_) Then out_.WriteLine "str_ub=" & CStr(UBound(Str_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "str_ub=NA err=0"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/p12i_cv1b_out.pph"
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
