' R11-2 host XT export
' generated by pphdecoding automation/vbs_bridge.py

' R11-2 host XT export
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r112_export.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
ret_save1_ = Doc_.SaveXTFile("D:/training/cgns/pphdecoding/_p12u_gate/r11_2_box_host.x_t")
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_save_box=" & CStr(ret_save1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
Set SN1_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/_p12u_gate/r11_2_box_reopen.x_t")
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn1__alive=" & CStr(Not (SN1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "reopen_box_sn=" & CStr(Not (SN1_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Set SN2_ = Doc_.OpenCadFile("D:/training/3dprint/FunHome-main/funHomeFan/cad/FunDeskFan/key v2.step")
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn2__alive=" & CStr(Not (SN2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW3_ = Doc_.WaitForWorker
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
ret_save2_ = Doc_.SaveXTFile("D:/training/cgns/pphdecoding/_p12u_gate/r11_2_step_host.x_t")
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_save_step=" & CStr(ret_save2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Set SN3_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/_p12u_gate/r11_2_step_reopen.x_t")
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn3__alive=" & CStr(Not (SN3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW4_ = Doc_.WaitForWorker
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "reopen_step_sn=" & CStr(Not (SN3_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
