' R13-1 host check
' generated by pphdecoding automation/vbs_bridge.py

' R13-1 host check
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r131_host.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/_p12u_gate/r12_1_nw340.x_t")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "snode_alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg_alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
ret_bam_ = Doc_.BuildAnalysisModel
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_bam=" & CStr(ret_bam_) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
Set VMDL_ = MG_.GetVMDL
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "vmdl__alive=" & CStr(Not (VMDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "vmdl_alive=" & CStr(Not (VMDL_ Is Nothing)) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Doc_.GetAllPartsBoundingBox BBox_, False
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
If IsArray(BBox_) Then out_.WriteLine "bbox=" & CStr(BBox_(0)) & "," & CStr(BBox_(3)) & " err=" & CStr(Err.Number) Else out_.WriteLine "bbox=NA"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r13_1_built.pph"
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
