' R1-3 xt_build
' generated by pphdecoding automation/vbs_bridge.py

' R1-3 xt_build
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r13_xt_build.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/tests/box/box.x_t")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.CreateMeshingGroup
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If MG_ Is Nothing Then Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
Doc_.GetAllPartsBoundingBox BBox_, False
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
If IsArray(BBox_) Then out_.WriteLine "bbox=" & CStr(BBox_(0)) & "," & CStr(BBox_(3)) & "," & CStr(BBox_(4)) & "," & CStr(BBox_(5)) & " err=" & CStr(Err.Number) Else out_.WriteLine "bbox=NA"
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
ret_bam_ = Doc_.BuildAnalysisModel
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_bam=" & CStr(ret_bam_) & " err=" & CStr(Err.Number)
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set VMDL_ = MG2_.GetVMDL
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "vmdl__alive=" & CStr(Not (VMDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MDL_ = MG2_.GetMDL
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mdl__alive=" & CStr(Not (MDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set OctParam_ = MG2_.GetOctParam
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "octparam__alive=" & CStr(Not (OctParam_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
OctParam_.Initialize
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
Param1_ = 3
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
OctParam_.SetOctType Param1_
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
Param1_ = 10000
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
OctParam_.SetMeshNum Param1_
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
Param1_ = 0
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
OctParam_.SetMinSize Param1_
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
ret_oct_ = MG2_.CreateOctree
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_oct=" & CStr(ret_oct_) & " err=" & CStr(Err.Number)
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
RetWW3_ = Doc_.WaitForWorker
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
Set OCT_ = MG2_.GetOctree
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct__alive=" & CStr(Not (OCT_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/xt_built.pph"
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
