' R2-1 mesh probe
' generated by pphdecoding automation/vbs_bridge.py

' R2-1 mesh probe
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r21_probe.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/tests/box/box.x_t")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_mode_oct=" & CStr(Doc_.SetModeOctree) & " err=" & CStr(Err.Number)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.CreateMeshingGroup
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_bam=" & CStr(Doc_.BuildAnalysisModel) & " err=" & CStr(Err.Number)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs_t=" & TypeName(MG2_.GetMeshingGroupSetting) & " err=" & CStr(Err.Number)
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
Set MGS_ = MG2_.GetMeshingGroupSetting
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs__alive=" & CStr(Not (MGS_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesher_t=" & TypeName(MGS_.GetMesher) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mdlmethod_t=" & TypeName(MGS_.GetMDLMethod) & " err=" & CStr(Err.Number)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "surfmesher_t=" & TypeName(MGS_.GetSurfMesher) & " err=" & CStr(Err.Number)
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "facet_spec_type=" & CStr(MGS_.GetFacetAccuracySpecificationType) & " err=" & CStr(Err.Number)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "facet_simple=" & CStr(MGS_.GetFacetUseSimpleSetting) & " err=" & CStr(Err.Number)
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct_exists0=" & CStr(MG2_.DoesMeshingOctreeExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
Set OctParam_ = MG2_.GetOctParam
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "octparam__alive=" & CStr(Not (OctParam_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetInit_ = OctParam_.Initialize
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "opt_type0=" & CStr(OctParam_.GetOctType) & " err=" & CStr(Err.Number)
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
P1_ = 3
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
OctParam_.SetOctType P1_
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
P1_ = 10000
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
OctParam_.SetMeshNum P1_
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
P1_ = 0
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
OctParam_.SetMinSize P1_
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "opt_type1=" & CStr(OctParam_.GetOctType) & " err=" & CStr(Err.Number)
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "opt_num1=" & CStr(OctParam_.GetMeshNum) & " err=" & CStr(Err.Number)
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "opt_min1=" & CStr(OctParam_.GetMinSize) & " err=" & CStr(Err.Number)
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_oct=" & CStr(MG2_.CreateOctree) & " err=" & CStr(Err.Number)
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
RetWW3_ = Doc_.WaitForWorker
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct_exists1=" & CStr(MG2_.DoesMeshingOctreeExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct_t=" & TypeName(MG2_.GetOctree) & " err=" & CStr(Err.Number)
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "groups_ub=" & CStr(UBound(Doc_.GetMeshingGroups)) & " err=" & CStr(Err.Number)
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "amg_t=" & TypeName(Doc_.GetActiveMeshingGroup) & " err=" & CStr(Err.Number)
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "amb=" & CStr(MG2_.IsAnalysisModelBuilt) & " err=" & CStr(Err.Number)
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_setmode_mesh=" & CStr(Doc_.SetModeMesh) & " err=" & CStr(Err.Number)
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "is_mode_oct_after=" & CStr(Doc_.IsModeOctree) & " err=" & CStr(Err.Number)
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_act=" & CStr(Doc_.SetActiveMeshingGroup(0, 0)) & " err=" & CStr(Err.Number)
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ret_mesh=" & CStr(MG2_.CreateMesh) & " err=" & CStr(Err.Number)
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
RetWW4_ = Doc_.WaitForWorker
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesh_exists=" & CStr(MG2_.DoesMeshExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesh_err=" & CStr(MG2_.DoesMeshErrorExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "ws=" & CStr(Doc_.GetWorkerStateString) & " err=" & CStr(Err.Number)
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
Set MG3_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg3__alive=" & CStr(Not (MG3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesh_exists2=" & CStr(MG3_.DoesMeshExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/xt_probe.pph"
out_.WriteLine "s049=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
