' R6-5 key probe
' generated by pphdecoding automation/vbs_bridge.py

' R6-5 key probe
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r65_keys.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS_ = MG_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs__alive=" & CStr(Not (MGS_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesher_before=" & CStr(MGS_.GetMesher) & " err=" & CStr(Err.Number)
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "surf_before=" & CStr(MGS_.GetSurfMesher) & " err=" & CStr(Err.Number)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "chord_before=" & CStr(MGS_.GetFacetSimpleChordTol) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "angle_before=" & CStr(MGS_.GetFacetSimpleMaxAngle) & " err=" & CStr(Err.Number)
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "width_before=" & CStr(MGS_.GetFacetSimpleMaxWidth) & " err=" & CStr(Err.Number)
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "detailw_before=" & CStr(MGS_.GetFacetUseDetailMaxWidth) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
P00_ = 7
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
MGS_.SetIntersectionDetectionDepth P00
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "edit0_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
Set MGS2_ = MG_.GetMeshingGroupSetting
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs2__alive=" & CStr(Not (MGS2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "chord_after=" & CStr(MGS2_.GetFacetSimpleChordTol) & " err=" & CStr(Err.Number)
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "angle_after=" & CStr(MGS2_.GetFacetSimpleMaxAngle) & " err=" & CStr(Err.Number)
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "width_after=" & CStr(MGS2_.GetFacetSimpleMaxWidth) & " err=" & CStr(Err.Number)
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "detailw_after=" & CStr(MGS2_.GetFacetUseDetailMaxWidth) & " err=" & CStr(Err.Number)
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r6_5_keyprobe.pph"
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
