' R7-4 host write check
' generated by pphdecoding automation/vbs_bridge.py

' R7-4 host write check
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r74_write.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/_p12u_gate/r7_4_written.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.QuerySNodeByName("Part")
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MDL_ = MG_.GetMDL
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mdl__alive=" & CStr(Not (MDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set OCT_ = MG_.GetOctree
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct__alive=" & CStr(Not (OCT_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS_ = MG_.GetMeshingGroupSetting
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs__alive=" & CStr(Not (MGS_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "read_USE_SIMPLE_SETTING=" & CStr(MGS_.GetFacetUseSimpleSetting) & " err=" & CStr(Err.Number)
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "read_MDL_METHOD=" & CStr(MGS_.GetMDLMethod) & " err=" & CStr(Err.Number)
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "read_SIMPLE_MAX_ANGLE=" & CStr(MGS_.GetFacetSimpleMaxAngle) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesh_exists=" & CStr(MG_.DoesMeshExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r7_4_rewritten.pph"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
