' R1-4 step_large
' generated by pphdecoding automation/vbs_bridge.py

' R1-4 step_large
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_matrix/r14_step_large.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.OpenCadFile("D:/training/3dprint/FunHome-main/funHomeFan/cad/FunDeskFan/top v5.step")
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
Set SN2_ = Doc_.QuerySNodeByName("Part")
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn2__alive=" & CStr(Not (SN2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set SN3_ = Doc_.QuerySNodeByName("top v5")
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn3__alive=" & CStr(Not (SN3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Parts_ = Doc_.GetSParts(False, False, False)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
If IsArray(Parts_) Then out_.WriteLine "parts_ub=" & CStr(UBound(Parts_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "parts_ub=NA err=0"
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
CreateObject("WScript.Shell").Run "cmd /c ping -n 6 127.0.0.1 > nul", 0, True
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Parts2_ = Doc_.GetSParts(False, False, False)
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
If IsArray(Parts2_) Then out_.WriteLine "parts2_ub=" & CStr(UBound(Parts2_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "parts2_ub=NA err=0"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Dim BBox_
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
Doc_.GetAllPartsBoundingBox BBox_, False
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
If IsArray(BBox_) Then out_.WriteLine "bbox_ub=" & CStr(UBound(BBox_)) & " b0=" & CStr(BBox_(0)) & " bL=" & CStr(BBox_(UBound(BBox_))) & " err=" & CStr(Err.Number) Else out_.WriteLine "bbox=NA err=" & CStr(Err.Number)
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_matrix/step_large_out.pph"
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
