' setter probe r33_enums
' generated by pphdecoding automation/vbs_bridge.py

' setter probe r33_enums
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/r33_enums.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG0_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg0__alive=" & CStr(Not (MG0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS0_ = MG0_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs0__alive=" & CStr(Not (MGS0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V0_ = "poly"
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
RetS0_ = MGS0_.ChangeMesher(V0_)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set0_ret=" & CStr(RetS0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
RetG0_ = MGS0_.GetMesher
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get0_val=" & CStr(RetG0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step0.pph"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Set MG1_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg1__alive=" & CStr(Not (MG1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS1_ = MG1_.GetMeshingGroupSetting
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs1__alive=" & CStr(Not (MGS1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V1_ = "oct"
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
RetS1_ = MGS1_.ChangeMesher(V1_)
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set1_ret=" & CStr(RetS1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
RetG1_ = MGS1_.GetMesher
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get1_val=" & CStr(RetG1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step1.pph"
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS2_ = MG2_.GetMeshingGroupSetting
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs2__alive=" & CStr(Not (MGS2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V2_ = "facet_base"
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
RetS2_ = MGS2_.ChangeSurfMesher(V2_)
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set2_ret=" & CStr(RetS2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
RetG2_ = MGS2_.GetSurfMesher
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get2_val=" & CStr(RetG2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step2.pph"
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
Set MG3_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg3__alive=" & CStr(Not (MG3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS3_ = MG3_.GetMeshingGroupSetting
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs3__alive=" & CStr(Not (MGS3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V3_ = "solid_base"
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
RetS3_ = MGS3_.ChangeSurfMesher(V3_)
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set3_ret=" & CStr(RetS3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
RetG3_ = MGS3_.GetSurfMesher
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get3_val=" & CStr(RetG3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step3.pph"
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
Set MG4_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg4__alive=" & CStr(Not (MG4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS4_ = MG4_.GetMeshingGroupSetting
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs4__alive=" & CStr(Not (MGS4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V4_ = "shape"
out_.WriteLine "s049=" & CStr(Err.Number)
Err.Clear
RetS4_ = MGS4_.SetVoxelOctRefineType(V4_)
out_.WriteLine "s050=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set4_ret=" & CStr(RetS4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s051=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s052=" & CStr(Err.Number)
Err.Clear
RetG4_ = MGS4_.GetVoxelOctRefineType
out_.WriteLine "s053=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get4_val=" & CStr(RetG4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s054=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s055=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step4.pph"
out_.WriteLine "s056=" & CStr(Err.Number)
Err.Clear
Set MG5_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s057=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg5__alive=" & CStr(Not (MG5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS5_ = MG5_.GetMeshingGroupSetting
out_.WriteLine "s058=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs5__alive=" & CStr(Not (MGS5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V5_ = "speed"
out_.WriteLine "s059=" & CStr(Err.Number)
Err.Clear
RetS5_ = MGS5_.SetVoxelOctRefineType(V5_)
out_.WriteLine "s060=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set5_ret=" & CStr(RetS5_) & " err=" & CStr(Err.Number)
out_.WriteLine "s061=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s062=" & CStr(Err.Number)
Err.Clear
RetG5_ = MGS5_.GetVoxelOctRefineType
out_.WriteLine "s063=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get5_val=" & CStr(RetG5_) & " err=" & CStr(Err.Number)
out_.WriteLine "s064=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s065=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step5.pph"
out_.WriteLine "s066=" & CStr(Err.Number)
Err.Clear
Set MG6_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s067=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg6__alive=" & CStr(Not (MG6_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS6_ = MG6_.GetMeshingGroupSetting
out_.WriteLine "s068=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs6__alive=" & CStr(Not (MGS6_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V6_ = "polyhedral"
out_.WriteLine "s069=" & CStr(Err.Number)
Err.Clear
RetS6_ = MGS6_.ChangeMesher(V6_)
out_.WriteLine "s070=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set6_ret=" & CStr(RetS6_) & " err=" & CStr(Err.Number)
out_.WriteLine "s071=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s072=" & CStr(Err.Number)
Err.Clear
RetG6_ = MGS6_.GetMesher
out_.WriteLine "s073=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get6_val=" & CStr(RetG6_) & " err=" & CStr(Err.Number)
out_.WriteLine "s074=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s075=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step6.pph"
out_.WriteLine "s076=" & CStr(Err.Number)
Err.Clear
Set MG7_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s077=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg7__alive=" & CStr(Not (MG7_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS7_ = MG7_.GetMeshingGroupSetting
out_.WriteLine "s078=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs7__alive=" & CStr(Not (MGS7_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V7_ = "facet"
out_.WriteLine "s079=" & CStr(Err.Number)
Err.Clear
RetS7_ = MGS7_.ChangeSurfMesher(V7_)
out_.WriteLine "s080=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set7_ret=" & CStr(RetS7_) & " err=" & CStr(Err.Number)
out_.WriteLine "s081=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s082=" & CStr(Err.Number)
Err.Clear
RetG7_ = MGS7_.GetSurfMesher
out_.WriteLine "s083=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get7_val=" & CStr(RetG7_) & " err=" & CStr(Err.Number)
out_.WriteLine "s084=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s085=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r33_enums/step7.pph"
out_.WriteLine "s086=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
