' R29 OCT_MESH
' generated by pphdecoding automation/vbs_bridge.py

' R29 OCT_MESH
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r29/r29.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG0_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg0__alive=" & CStr(Not (MG0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS0_ = MG0_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs0__alive=" & CStr(Not (MGS0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V0_ = 0.7
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
MGS0_.SetSolidFacetLengthFactor V0_
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set0_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step0.pph"
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save0_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
Set MG1_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg1__alive=" & CStr(Not (MG1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS1_ = MG1_.GetMeshingGroupSetting
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs1__alive=" & CStr(Not (MGS1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V1_ = 9.0
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
MGS1_.SetSolidFacetAngle V1_
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set1_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step1.pph"
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save1_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS2_ = MG2_.GetMeshingGroupSetting
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs2__alive=" & CStr(Not (MGS2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V2_ = 7.0
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
MGS2_.SetSolidFacetMaxWidthFactor V2_
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set2_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step2.pph"
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save2_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
Set MG3_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg3__alive=" & CStr(Not (MG3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS3_ = MG3_.GetMeshingGroupSetting
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs3__alive=" & CStr(Not (MGS3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V3_ = True
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
MGS3_.SetSolidFacetSpecifyEachRegionFlag V3_
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set3_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step3.pph"
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save3_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
Set MG4_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg4__alive=" & CStr(Not (MG4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS4_ = MG4_.GetMeshingGroupSetting
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs4__alive=" & CStr(Not (MGS4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V4_ = True
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
MGS4_.SetCompleteParallelFlag V4_
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set4_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step4.pph"
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save4_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
Set MG5_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg5__alive=" & CStr(Not (MG5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS5_ = MG5_.GetMeshingGroupSetting
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs5__alive=" & CStr(Not (MGS5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V5_ = 3
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
MGS5_.SetVoxelOctRefineType V5_
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set5_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r29/step5.pph"
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "save5_err=" & CStr(Err.Number) & " err=" & CStr(Err.Number)
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
