' R1-7 mdl
' generated by pphdecoding automation/vbs_bridge.py

' R1-7 mdl
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_reopen/r1_mdl.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/_p12u_reopen/mdl.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.QuerySNodeByName("Part")
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MG_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg__alive=" & CStr(Not (MG_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MDL_ = MG_.GetMDL
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mdl__alive=" & CStr(Not (MDL_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set OCT_ = MG_.GetOctree
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "oct__alive=" & CStr(Not (OCT_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mesh_exists=" & CStr(MG_.DoesMeshExist) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Param1_ = False
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
Doc_.GetAllPartsBoundingBox BBox_, False
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
If IsArray(BBox_) Then out_.WriteLine "bbox_ub=" & CStr(UBound(BBox_)) & " b0=" & CStr(BBox_(0)) & " bL=" & CStr(BBox_(UBound(BBox_))) & " err=" & CStr(Err.Number) Else out_.WriteLine "bbox=NA"
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Parts_ = Doc_.GetSParts(False, False, False)
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
If IsArray(Parts_) Then out_.WriteLine "parts_ub=" & CStr(UBound(Parts_)) & " err=" & CStr(Err.Number) Else out_.WriteLine "parts_ub=NA err=0"
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_reopen/mdl_out.pph"
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
