' setter probe unit_r301
' generated by pphdecoding automation/vbs_bridge.py

' setter probe unit_r301
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/unit_r301/unit_r301.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG0_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg0__alive=" & CStr(Not (MG0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS0_ = MG0_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs0__alive=" & CStr(Not (MGS0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V0_ = "speed"
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
RetS0_ = MGS0_.SetVoxelOctRefineType(V0_)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set0_ret=" & CStr(RetS0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
RetG0_ = MGS0_.GetVoxelOctRefineType
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get0_val=" & CStr(RetG0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/unit_r301/step0.pph"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
