#!/usr/bin/env python3
"""scFLOWpre VBScript 桥。

scFLOWpre 通过 VBScript 暴露自动化接口（File → Execute VBScript / 录制
history.vbs）。本模块提供：

- 纯函数：构建/写出/读取 VBScript 文件；
- ``VbsBridge``：定位 scFLOWpre、构造启动命令，并提供三种执行后端：

  - ``manual``：写出脚本并提示人工执行（最可靠，零侵入）；
  - ``cli``：按可配置参数直接带脚本启动（默认 ``-vbs``，待实机确认参数名）；
  - ``gui``：pywinauto 驱动菜单 File → Execute VBScript（对话框布局可注入 hook）。
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional

import scflowpre_probe
from automation.history_vbs import decode_vbs

DEFAULT_SCRIPT_ARG = "-vbs"


def build_vbs(actions: list[str], title: str = "scFLOWpre automation") -> str:
    """把动作行组装成 VBScript 文本（CRLF）。"""
    lines = [
        f"' {title}",
        "' generated by pphdecoding automation/vbs_bridge.py",
        "",
    ]
    for action in actions:
        lines.append(str(action).rstrip())
    return "\r\n".join(lines) + "\r\n"


def write_vbs_file(actions: list[str], path: str | Path,
                   title: str = "scFLOWpre automation") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    # scFLOWpre 的 VBScript 引擎要求 UTF-16LE + BOM（与 history.vbs 一致）。
    # 用 write_bytes 避免文本模式把 \r\n 再转成 \r\r\n。
    path.write_bytes(build_vbs(actions, title).encode("utf-16"))
    return path


def read_vbs_lines(path: str | Path) -> list[str]:
    """读取 VBS 文件，去掉注释/空行，并拼接续行（行尾 ``_``）。"""
    text = decode_vbs(Path(path).read_bytes())
    logical: list[str] = []
    pending = ""
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("'") or line.lower().startswith("rem "):
            continue
        if pending:
            line = pending + " " + line
            pending = ""
        if line.rstrip()[-2:] == " _":
            pending = line.rstrip()[:-2].rstrip()
            continue
        logical.append(line)
    if pending:
        logical.append(pending)
    return logical


@dataclass
class VbsBridge:
    """定位 scFLOWpre 并执行 VBScript 的桥。"""

    install_dir: Optional[str] = None
    exe_name: str = "scFLOWpre_Bx64net.exe"
    script_arg: str = DEFAULT_SCRIPT_ARG
    timeout: float = 120.0
    _exe_cache: Optional[Path] = field(default=None, repr=False)

    def exe_path(self) -> Optional[Path]:
        if self._exe_cache is not None:
            return self._exe_cache
        root = Path(self.install_dir) if self.install_dir else None
        if root is None:
            root = scflowpre_probe.find_install()
        if root is None:
            return None
        exe = root / scflowpre_probe.PROGRAMS_SUBDIR / self.exe_name
        self._exe_cache = exe if exe.is_file() else None
        return self._exe_cache

    def launch_command(self, vbs_path: str | Path,
                       script_args: Optional[list[str]] = None) -> list[str]:
        """构造启动命令；脚本参数名可配置（默认 ``-vbs``）。"""
        exe = self.exe_path()
        if exe is None:
            raise FileNotFoundError("scFLOWpre 未安装或未找到")
        args = list(script_args) if script_args is not None \
            else [self.script_arg, str(vbs_path)]
        return [str(exe), *args]

    def execute(self, vbs_path: str | Path, *, backend: str = "manual",
                script_args: Optional[list[str]] = None,
                gui_hooks: Optional[dict] = None) -> dict:
        """执行 VBScript；backend ∈ {manual, cli, gui}。"""
        vbs_path = Path(vbs_path)
        if not vbs_path.is_file():
            raise FileNotFoundError(vbs_path)
        if backend == "cli":
            cmd = self.launch_command(vbs_path, script_args)
            proc = subprocess.run(cmd, capture_output=True, text=True,
                                  timeout=self.timeout, check=False)
            return {"backend": "cli", "command": cmd,
                    "returncode": proc.returncode,
                    "stdout": proc.stdout, "stderr": proc.stderr}
        if backend == "gui":
            return self._execute_gui(vbs_path, hooks=gui_hooks or {})
        return {"backend": "manual", "script": str(vbs_path),
                "hint": "请在 scFLOWpre 中执行 File → Execute VBScript，"
                        "选择该脚本文件"}

    def _execute_gui(self, vbs_path: Path, hooks: dict) -> dict:
        """pywinauto 驱动；菜单文本与对话框填充均可注入。"""
        exe = self.exe_path()
        if exe is None:
            raise FileNotFoundError("scFLOWpre 未安装或未找到")
        try:
            import pywinauto
            from pywinauto.application import Application
        except ImportError as exc:  # pragma: no cover - 依赖可选
            raise RuntimeError("pywinauto 未安装，无法使用 gui 后端") from exc

        app = Application(backend="uia").start(str(exe))
        win = app.window(title_re=".*scFLOWpre.*", timeout=self.timeout)
        win.wait("visible", timeout=self.timeout)
        menu = hooks.get("menu") or {"file": "File",
                                     "execute_vbs": "Execute VBScript"}
        win.menu_select(f"{menu['file']}->{menu['execute_vbs']}")
        dlg = app.window(title_re=hooks.get("dlg_title_re", ".*VBS.*"),
                         timeout=self.timeout)
        dlg.wait("visible", timeout=self.timeout)
        fill = hooks.get("fill_dialog")
        if fill is None:
            try:
                dlg.child_window(class_name="Edit").set_edit_text(str(vbs_path))
                ok = hooks.get("ok_button", "OK")
                dlg.child_window(title=ok).click()
            except Exception:  # noqa: BLE001
                return {"backend": "gui", "status": "dialog_fill_failed",
                        "script": str(vbs_path)}
        else:
            fill(dlg, vbs_path)
        return {"backend": "gui", "status": "submitted",
                "script": str(vbs_path)}


def main(argv: Optional[list[str]] = None) -> int:
    import argparse
    import sys

    ap = argparse.ArgumentParser(description="scFLOWpre VBScript 桥")
    ap.add_argument("--actions", nargs="*", default=[],
                    help="VBS 动作行（未提供则读 --input）")
    ap.add_argument("--input", help="已有 .vbs 文件（读取动作行）")
    ap.add_argument("--output", required=True, help="输出 .vbs 路径")
    args = ap.parse_args(argv)
    if args.input:
        actions = read_vbs_lines(args.input)
    else:
        actions = args.actions
    write_vbs_file(actions, args.output)
    print(f"written {args.output} ({len(actions)} actions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
