' R1-1
' generated by pphdecoding automation/vbs_bridge.py

' R1-1
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_cmp/r1_host.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Set SN_ = Doc_.OpenCadFile("D:/training/cgns/pphdecoding/_p12r_step/cadthru_base_v7.x_t")
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "sn__alive=" & CStr(Not (SN_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Doc_.SetModePart
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
RetWW2_ = Doc_.WaitForWorker
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_cmp/host_out.pph"
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
