' setter probe r30_voxel
' generated by pphdecoding automation/vbs_bridge.py

' setter probe r30_voxel
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/r30_voxel.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG0_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg0__alive=" & CStr(Not (MG0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS0_ = MG0_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs0__alive=" & CStr(Not (MGS0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetG0_ = MGS0_.GetVoxelOctRefineType
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get0_val=" & CStr(RetG0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/step0.pph"
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
Set MG1_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg1__alive=" & CStr(Not (MG1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS1_ = MG1_.GetMeshingGroupSetting
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs1__alive=" & CStr(Not (MGS1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V1_ = "speed"
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
RetS1_ = MGS1_.SetVoxelOctRefineType(V1_)
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set1_ret=" & CStr(RetS1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
RetG1_ = MGS1_.GetVoxelOctRefineType
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get1_val=" & CStr(RetG1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/step1.pph"
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS2_ = MG2_.GetMeshingGroupSetting
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs2__alive=" & CStr(Not (MGS2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V2_ = "shape"
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
RetS2_ = MGS2_.SetVoxelOctRefineType(V2_)
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set2_ret=" & CStr(RetS2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
RetG2_ = MGS2_.GetVoxelOctRefineType
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get2_val=" & CStr(RetG2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/step2.pph"
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
Set MG3_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg3__alive=" & CStr(Not (MG3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS3_ = MG3_.GetMeshingGroupSetting
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs3__alive=" & CStr(Not (MGS3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V3_ = "Speed"
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
RetS3_ = MGS3_.SetVoxelOctRefineType(V3_)
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set3_ret=" & CStr(RetS3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
RetG3_ = MGS3_.GetVoxelOctRefineType
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get3_val=" & CStr(RetG3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/step3.pph"
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
Set MG4_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg4__alive=" & CStr(Not (MG4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS4_ = MG4_.GetMeshingGroupSetting
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs4__alive=" & CStr(Not (MGS4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V4_ = 0
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
RetS4_ = MGS4_.SetVoxelOctRefineType(V4_)
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set4_ret=" & CStr(RetS4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
RetG4_ = MGS4_.GetVoxelOctRefineType
out_.WriteLine "s049=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get4_val=" & CStr(RetG4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s050=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s051=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r30_voxel/step4.pph"
out_.WriteLine "s052=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
