' setter probe r32_keys
' generated by pphdecoding automation/vbs_bridge.py

' setter probe r32_keys
On Error Resume Next
Set fso_ = CreateObject("Scripting.FileSystemObject")
Set out_ = fso_.CreateTextFile("D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/r32_keys.log", True)
out_.WriteLine "start"
Set App_ = GetApplication()
out_.WriteLine "s001=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "app__alive=" & CStr(Not (App_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
If App_ Is Nothing Then Set App_ = CreateObject("scFLOWpre_Bx64net.Application.2025")
out_.WriteLine "s002=" & CStr(Err.Number)
Err.Clear
Set Doc_ = App_.GetDocument
out_.WriteLine "s003=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "doc__alive=" & CStr(Not (Doc_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
RetWW0_ = Doc_.WaitForWorker
out_.WriteLine "s004=" & CStr(Err.Number)
Err.Clear
Doc_.OpenProject "D:/training/cgns/pphdecoding/box.pph", False
out_.WriteLine "s005=" & CStr(Err.Number)
Err.Clear
RetWW1_ = Doc_.WaitForWorker
out_.WriteLine "s006=" & CStr(Err.Number)
Err.Clear
Set MG0_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s007=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg0__alive=" & CStr(Not (MG0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS0_ = MG0_.GetMeshingGroupSetting
out_.WriteLine "s008=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs0__alive=" & CStr(Not (MGS0_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V0_ = 0.25
out_.WriteLine "s009=" & CStr(Err.Number)
Err.Clear
RetS0_ = MGS0_.SetFacetSimpleChordTol(V0_)
out_.WriteLine "s010=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set0_ret=" & CStr(RetS0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s011=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s012=" & CStr(Err.Number)
Err.Clear
RetG0_ = MGS0_.GetFacetSimpleChordTol
out_.WriteLine "s013=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get0_val=" & CStr(RetG0_) & " err=" & CStr(Err.Number)
out_.WriteLine "s014=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s015=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step0.pph"
out_.WriteLine "s016=" & CStr(Err.Number)
Err.Clear
Set MG1_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s017=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg1__alive=" & CStr(Not (MG1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS1_ = MG1_.GetMeshingGroupSetting
out_.WriteLine "s018=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs1__alive=" & CStr(Not (MGS1_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V1_ = 8.0
out_.WriteLine "s019=" & CStr(Err.Number)
Err.Clear
RetS1_ = MGS1_.SetFacetSimpleMaxAngle(V1_)
out_.WriteLine "s020=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set1_ret=" & CStr(RetS1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s021=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s022=" & CStr(Err.Number)
Err.Clear
RetG1_ = MGS1_.GetFacetSimpleMaxAngle
out_.WriteLine "s023=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get1_val=" & CStr(RetG1_) & " err=" & CStr(Err.Number)
out_.WriteLine "s024=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s025=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step1.pph"
out_.WriteLine "s026=" & CStr(Err.Number)
Err.Clear
Set MG2_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s027=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg2__alive=" & CStr(Not (MG2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS2_ = MG2_.GetMeshingGroupSetting
out_.WriteLine "s028=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs2__alive=" & CStr(Not (MGS2_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V2_ = 9.0
out_.WriteLine "s029=" & CStr(Err.Number)
Err.Clear
RetS2_ = MGS2_.SetFacetSimpleMaxWidth(V2_)
out_.WriteLine "s030=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set2_ret=" & CStr(RetS2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s031=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s032=" & CStr(Err.Number)
Err.Clear
RetG2_ = MGS2_.GetFacetSimpleMaxWidth
out_.WriteLine "s033=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get2_val=" & CStr(RetG2_) & " err=" & CStr(Err.Number)
out_.WriteLine "s034=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s035=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step2.pph"
out_.WriteLine "s036=" & CStr(Err.Number)
Err.Clear
Set MG3_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s037=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg3__alive=" & CStr(Not (MG3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS3_ = MG3_.GetMeshingGroupSetting
out_.WriteLine "s038=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs3__alive=" & CStr(Not (MGS3_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V3_ = False
out_.WriteLine "s039=" & CStr(Err.Number)
Err.Clear
RetS3_ = MGS3_.SetFacetUseDetailMaxWidth(V3_)
out_.WriteLine "s040=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set3_ret=" & CStr(RetS3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s041=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s042=" & CStr(Err.Number)
Err.Clear
RetG3_ = MGS3_.GetFacetUseDetailMaxWidth
out_.WriteLine "s043=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get3_val=" & CStr(RetG3_) & " err=" & CStr(Err.Number)
out_.WriteLine "s044=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s045=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step3.pph"
out_.WriteLine "s046=" & CStr(Err.Number)
Err.Clear
Set MG4_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s047=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg4__alive=" & CStr(Not (MG4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS4_ = MG4_.GetMeshingGroupSetting
out_.WriteLine "s048=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs4__alive=" & CStr(Not (MGS4_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V4_ = False
out_.WriteLine "s049=" & CStr(Err.Number)
Err.Clear
RetS4_ = MGS4_.SetFacetUseSimpleSetting(V4_)
out_.WriteLine "s050=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set4_ret=" & CStr(RetS4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s051=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s052=" & CStr(Err.Number)
Err.Clear
RetG4_ = MGS4_.GetFacetUseSimpleSetting
out_.WriteLine "s053=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get4_val=" & CStr(RetG4_) & " err=" & CStr(Err.Number)
out_.WriteLine "s054=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s055=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step4.pph"
out_.WriteLine "s056=" & CStr(Err.Number)
Err.Clear
Set MG5_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s057=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg5__alive=" & CStr(Not (MG5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS5_ = MG5_.GetMeshingGroupSetting
out_.WriteLine "s058=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs5__alive=" & CStr(Not (MGS5_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V5_ = 0
out_.WriteLine "s059=" & CStr(Err.Number)
Err.Clear
RetS5_ = MGS5_.SetMDLMethod(V5_)
out_.WriteLine "s060=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set5_ret=" & CStr(RetS5_) & " err=" & CStr(Err.Number)
out_.WriteLine "s061=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s062=" & CStr(Err.Number)
Err.Clear
RetG5_ = MGS5_.GetMDLMethod
out_.WriteLine "s063=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get5_val=" & CStr(RetG5_) & " err=" & CStr(Err.Number)
out_.WriteLine "s064=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s065=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step5.pph"
out_.WriteLine "s066=" & CStr(Err.Number)
Err.Clear
Set MG6_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s067=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg6__alive=" & CStr(Not (MG6_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS6_ = MG6_.GetMeshingGroupSetting
out_.WriteLine "s068=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs6__alive=" & CStr(Not (MGS6_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V6_ = 20.0
out_.WriteLine "s069=" & CStr(Err.Number)
Err.Clear
RetS6_ = MGS6_.SetFacetDetailChordAngle(V6_)
out_.WriteLine "s070=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set6_ret=" & CStr(RetS6_) & " err=" & CStr(Err.Number)
out_.WriteLine "s071=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s072=" & CStr(Err.Number)
Err.Clear
RetG6_ = MGS6_.GetFacetDetailChordAngle
out_.WriteLine "s073=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get6_val=" & CStr(RetG6_) & " err=" & CStr(Err.Number)
out_.WriteLine "s074=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s075=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step6.pph"
out_.WriteLine "s076=" & CStr(Err.Number)
Err.Clear
Set MG7_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s077=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg7__alive=" & CStr(Not (MG7_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS7_ = MG7_.GetMeshingGroupSetting
out_.WriteLine "s078=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs7__alive=" & CStr(Not (MGS7_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V7_ = 0.3
out_.WriteLine "s079=" & CStr(Err.Number)
Err.Clear
RetS7_ = MGS7_.SetAFFaceterLengthFactor(V7_)
out_.WriteLine "s080=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set7_ret=" & CStr(RetS7_) & " err=" & CStr(Err.Number)
out_.WriteLine "s081=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s082=" & CStr(Err.Number)
Err.Clear
RetG7_ = MGS7_.GetAFFaceterLengthFactor
out_.WriteLine "s083=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get7_val=" & CStr(RetG7_) & " err=" & CStr(Err.Number)
out_.WriteLine "s084=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s085=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step7.pph"
out_.WriteLine "s086=" & CStr(Err.Number)
Err.Clear
Set MG8_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s087=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg8__alive=" & CStr(Not (MG8_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS8_ = MG8_.GetMeshingGroupSetting
out_.WriteLine "s088=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs8__alive=" & CStr(Not (MGS8_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V8_ = 9
out_.WriteLine "s089=" & CStr(Err.Number)
Err.Clear
RetS8_ = MGS8_.SetIntersectionDetectionDepth(V8_)
out_.WriteLine "s090=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set8_ret=" & CStr(RetS8_) & " err=" & CStr(Err.Number)
out_.WriteLine "s091=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s092=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step8.pph"
out_.WriteLine "s093=" & CStr(Err.Number)
Err.Clear
Set MG9_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s094=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg9__alive=" & CStr(Not (MG9_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS9_ = MG9_.GetMeshingGroupSetting
out_.WriteLine "s095=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs9__alive=" & CStr(Not (MGS9_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V9_ = 12.0
out_.WriteLine "s096=" & CStr(Err.Number)
Err.Clear
RetS9_ = MGS9_.SetAFFaceterMinimumAngle(V9_)
out_.WriteLine "s097=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set9_ret=" & CStr(RetS9_) & " err=" & CStr(Err.Number)
out_.WriteLine "s098=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s099=" & CStr(Err.Number)
Err.Clear
RetG9_ = MGS9_.GetAFFaceterMinimumAngle
out_.WriteLine "s100=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get9_val=" & CStr(RetG9_) & " err=" & CStr(Err.Number)
out_.WriteLine "s101=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s102=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step9.pph"
out_.WriteLine "s103=" & CStr(Err.Number)
Err.Clear
Set MG10_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s104=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg10__alive=" & CStr(Not (MG10_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS10_ = MG10_.GetMeshingGroupSetting
out_.WriteLine "s105=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs10__alive=" & CStr(Not (MGS10_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V10_ = 0.3
out_.WriteLine "s106=" & CStr(Err.Number)
Err.Clear
RetS10_ = MGS10_.SetAFFaceterLengthFactorForOctree(V10_)
out_.WriteLine "s107=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set10_ret=" & CStr(RetS10_) & " err=" & CStr(Err.Number)
out_.WriteLine "s108=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s109=" & CStr(Err.Number)
Err.Clear
RetG10_ = MGS10_.GetAFFaceterLengthFactorForOctree
out_.WriteLine "s110=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get10_val=" & CStr(RetG10_) & " err=" & CStr(Err.Number)
out_.WriteLine "s111=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s112=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step10.pph"
out_.WriteLine "s113=" & CStr(Err.Number)
Err.Clear
Set MG11_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s114=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg11__alive=" & CStr(Not (MG11_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS11_ = MG11_.GetMeshingGroupSetting
out_.WriteLine "s115=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs11__alive=" & CStr(Not (MGS11_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V11_ = 8.0
out_.WriteLine "s116=" & CStr(Err.Number)
Err.Clear
RetS11_ = MGS11_.SetAFFaceterMinimumAngleForOctree(V11_)
out_.WriteLine "s117=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set11_ret=" & CStr(RetS11_) & " err=" & CStr(Err.Number)
out_.WriteLine "s118=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s119=" & CStr(Err.Number)
Err.Clear
RetG11_ = MGS11_.GetAFFaceterMinimumAngleForOctree
out_.WriteLine "s120=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get11_val=" & CStr(RetG11_) & " err=" & CStr(Err.Number)
out_.WriteLine "s121=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s122=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step11.pph"
out_.WriteLine "s123=" & CStr(Err.Number)
Err.Clear
Set MG12_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s124=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg12__alive=" & CStr(Not (MG12_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS12_ = MG12_.GetMeshingGroupSetting
out_.WriteLine "s125=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs12__alive=" & CStr(Not (MGS12_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V12_ = 0.7
out_.WriteLine "s126=" & CStr(Err.Number)
Err.Clear
RetS12_ = MGS12_.SetSolidFacetLengthFactor(V12_)
out_.WriteLine "s127=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set12_ret=" & CStr(RetS12_) & " err=" & CStr(Err.Number)
out_.WriteLine "s128=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s129=" & CStr(Err.Number)
Err.Clear
RetG12_ = MGS12_.GetSolidFacetLengthFactor
out_.WriteLine "s130=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get12_val=" & CStr(RetG12_) & " err=" & CStr(Err.Number)
out_.WriteLine "s131=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s132=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step12.pph"
out_.WriteLine "s133=" & CStr(Err.Number)
Err.Clear
Set MG13_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s134=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg13__alive=" & CStr(Not (MG13_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS13_ = MG13_.GetMeshingGroupSetting
out_.WriteLine "s135=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs13__alive=" & CStr(Not (MGS13_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V13_ = 9.0
out_.WriteLine "s136=" & CStr(Err.Number)
Err.Clear
RetS13_ = MGS13_.SetSolidFacetAngle(V13_)
out_.WriteLine "s137=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set13_ret=" & CStr(RetS13_) & " err=" & CStr(Err.Number)
out_.WriteLine "s138=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s139=" & CStr(Err.Number)
Err.Clear
RetG13_ = MGS13_.GetSolidFacetAngle
out_.WriteLine "s140=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get13_val=" & CStr(RetG13_) & " err=" & CStr(Err.Number)
out_.WriteLine "s141=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s142=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step13.pph"
out_.WriteLine "s143=" & CStr(Err.Number)
Err.Clear
Set MG14_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s144=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg14__alive=" & CStr(Not (MG14_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS14_ = MG14_.GetMeshingGroupSetting
out_.WriteLine "s145=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs14__alive=" & CStr(Not (MGS14_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V14_ = 7.0
out_.WriteLine "s146=" & CStr(Err.Number)
Err.Clear
RetS14_ = MGS14_.SetSolidFacetMaxWidthFactor(V14_)
out_.WriteLine "s147=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set14_ret=" & CStr(RetS14_) & " err=" & CStr(Err.Number)
out_.WriteLine "s148=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s149=" & CStr(Err.Number)
Err.Clear
RetG14_ = MGS14_.GetSolidFacetMaxWidthFactor
out_.WriteLine "s150=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get14_val=" & CStr(RetG14_) & " err=" & CStr(Err.Number)
out_.WriteLine "s151=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s152=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step14.pph"
out_.WriteLine "s153=" & CStr(Err.Number)
Err.Clear
Set MG15_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s154=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg15__alive=" & CStr(Not (MG15_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS15_ = MG15_.GetMeshingGroupSetting
out_.WriteLine "s155=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs15__alive=" & CStr(Not (MGS15_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V15_ = True
out_.WriteLine "s156=" & CStr(Err.Number)
Err.Clear
RetS15_ = MGS15_.SetSolidFacetSpecifyEachRegionFlag(V15_)
out_.WriteLine "s157=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set15_ret=" & CStr(RetS15_) & " err=" & CStr(Err.Number)
out_.WriteLine "s158=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s159=" & CStr(Err.Number)
Err.Clear
RetG15_ = MGS15_.GetSolidFacetSpecifyEachRegionFlag
out_.WriteLine "s160=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get15_val=" & CStr(RetG15_) & " err=" & CStr(Err.Number)
out_.WriteLine "s161=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s162=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step15.pph"
out_.WriteLine "s163=" & CStr(Err.Number)
Err.Clear
Set MG16_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s164=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg16__alive=" & CStr(Not (MG16_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS16_ = MG16_.GetMeshingGroupSetting
out_.WriteLine "s165=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs16__alive=" & CStr(Not (MGS16_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V16_ = True
out_.WriteLine "s166=" & CStr(Err.Number)
Err.Clear
RetS16_ = MGS16_.SetCompleteParallelFlag(V16_)
out_.WriteLine "s167=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set16_ret=" & CStr(RetS16_) & " err=" & CStr(Err.Number)
out_.WriteLine "s168=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s169=" & CStr(Err.Number)
Err.Clear
RetG16_ = MGS16_.GetCompleteParallelFlag
out_.WriteLine "s170=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get16_val=" & CStr(RetG16_) & " err=" & CStr(Err.Number)
out_.WriteLine "s171=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s172=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step16.pph"
out_.WriteLine "s173=" & CStr(Err.Number)
Err.Clear
Set MG17_ = Doc_.QueryMeshingGroupByIndex(0)
out_.WriteLine "s174=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mg17__alive=" & CStr(Not (MG17_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
Set MGS17_ = MG17_.GetMeshingGroupSetting
out_.WriteLine "s175=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "mgs17__alive=" & CStr(Not (MGS17_ Is Nothing)) & " err=" & CStr(Err.Number)
Err.Clear
V17_ = "speed"
out_.WriteLine "s176=" & CStr(Err.Number)
Err.Clear
RetS17_ = MGS17_.SetVoxelOctRefineType(V17_)
out_.WriteLine "s177=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "set17_ret=" & CStr(RetS17_) & " err=" & CStr(Err.Number)
out_.WriteLine "s178=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s179=" & CStr(Err.Number)
Err.Clear
RetG17_ = MGS17_.GetVoxelOctRefineType
out_.WriteLine "s180=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "get17_val=" & CStr(RetG17_) & " err=" & CStr(Err.Number)
out_.WriteLine "s181=" & CStr(Err.Number)
Err.Clear
Err.Clear
out_.WriteLine "s182=" & CStr(Err.Number)
Err.Clear
Doc_.SaveProject "D:/training/cgns/pphdecoding/_p12u_gate/r32_keys/step17.pph"
out_.WriteLine "s183=" & CStr(Err.Number)
Err.Clear
out_.WriteLine "end"
out_.Close
